services:
  postgres:
    image: postgres:16.6-alpine
    env_file: ".env"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - flea-market:/var/lib/postgresql/data
    ports:
      - "${LOCAL_PORT_POSTGRES}:${POSTGRES_PORT}"
    restart: unless-stopped
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - api_server
    command: ['-g', 'daemon off;']
  api_server:
    container_name: api_server
    env_file: "./.env"
    build:
      context: ./../../
      dockerfile: deployments/development/gobuild.Dockerfile
      target: dev-runner
      args:
        APPLICATION_NAME: api
    command: "-a=api_server:${SERVER_PORT} -d=${SERVER_DB_DNS}"
    expose:
      - ${SERVER_PORT}
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  flea-market: